### PR TITLE
Feature: Add common logger utils for tricorder go

### PR DESCRIPTION
**Pull request by jmzwcn**

### CODE REVIEW

**Review by nascentcore-eng — COMMENTED** [review]
There are too many APIs,

Please just provide the exact set of logging APIs that are:
1. Identical with the std lib's `log` APIs, i.e., the vanilla `log` APIs in standard lib, logrus also has the same compatibility.
```
// We need this API to be identical to standard logging API
import "github.com/tricorder/src/utils/log"
log.Infof("...", ...)
log.Errorf("...", ...)
```
3. Just enough APIs to be used, not extra ones

Additionally, you need to provide a linter to prevent people from using other forms of logging APIs.

**Comment by jmzwcn** [comment]
> There are too many APIs,
> 
> Please just provide the exact set of logging APIs that are:
> 
> 1. Identical with the std lib's `log` APIs, i.e., the vanilla `log` APIs in standard lib, logrus also has the same compatibility.
> 
> ```
> // We need this API to be identical to standard logging API
> import "github.com/tricorder/src/utils/log"
> log.Infof("...", ...)
> log.Errorf("...", ...)
> ```
> 
> 3. Just enough APIs to be used, not extra ones
> 

I think we should provide the same features(APIs) compared with standard logrus package, but easier to use for tricorder.
Original library is here: https://github.com/sirupsen/logrus/blob/master/exported.go

**Comment by nascentcore-eng** [comment]
Hasn't been any activity for a while. Close.

**Comment by jmzwcn** [comment]
> 
> Additionally, you need to provide a linter to prevent people from using other forms of logging APIs.

Already added a linter for this logger.

**Review by nascentcore-eng — APPROVED** [review]

**Pull request merged**
